# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=user
      - POSTGRES_DB=db

    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"